# GRPO
model_name_GRPO: GRPO

# Data Config
train_data_path: /home/ubuntu/LTL/My_Python/AAAI2025/data/test_scenario_data
val_data_path: /home/ubuntu/LTL/My_Python/AAAI2025/data/test_scenario_data
anchor_path: /home/ubuntu/LTL/My_Python/AAAI2025/data/cluster_64_center_dict.pkl
log_dir: ./train_GRPO_log  # 输出的路径文件夹


# Wandb Config
use_wandb: False
username: null
project: null

# Checkpoint Config
init_from: null

# Model Config
agents_len: 32
future_len: 40
action_len: 2
encoder_layers: 6
prediction_type: sample
encoder_version: v2 # v1: GRU, v2: MLP

# Diffusion Params
diffusion_steps: 50
schedule_type: cosine
schedule_s: 0
schedule_e: 1
schedule_tau: 1

action_mean: [0.0, 0.0]
action_std: [1.0, 0.15]
clamp_value: 5.0

# Training Params
seed: 42
batch_size: 3
num_workers: 16
lr: 0.0002
weight_decay: 0.01
epochs: 32
lr_warmup_step: 1000
lr_step_freq: 1000
lr_step_gamma: 0.98

train_encoder: True # 是否训练encoder
train_denoiser: True # 是否训练denoiser
train_predictor: False # 是否训练predictor

# new
decoder_drop_path_rate: 0.1
predicted_agents_num: 32
hidden_dim: 256
num_heads: 8
num_layers: 6
decoder_depth: 4

# GRPO Config
group_size: 6  # 每个样本生成的轨迹数量
beta: 0.1  # KL散度的权重

